FROM browserless/chrome:latest
EXPOSE 3000
ENV MAX_CONCURRENT_SESSIONS 3
ENV DEFAULT_HEADLESS false
ENV ENABLE_DEBUGGER=false
ENV DEFAULT_USER_DATA_DIR=tmp
ENV ENABLE_API_GET=true
ENV CONNECTION_TIMEOUT=360000
